### ISSUE TITLE
[New] 添加Julia镜像

### ISSUE THREAD

**Issue by Roger-luo** [ustclug/mirrorrequest#29]
[julia官网下载](http://julialang.org/downloads/)

METADATA.jl已经在GitHub上托管了，但是由于编译器的安装包在aws上有时候慢的可以...

**Comment by Roger-luo** [comment]
把METADATA.jl里的url在科大这边做成镜像不知道有没有可能。。。

**Comment by liuhuancom** [comment]
希望添加

**Comment by icyblade** [comment]
附议

**Comment by daxinnan** [comment]
两年之后再次附议！！！大型机上网络时好时坏，安装packages太慢了。

**Comment by zhsj** [comment]
两年过去了，有没有好的方法同步了呢？

**Comment by Roger-luo** [comment]
@staticfloat 在写Dockerfile，我们可以等一下他

**Comment by staticfloat** [comment]
@Roger-luo @zhsj I have opened #50.  I believe this works okay (I tested a small amount of downloading, but did not wait for it to finish) please let me know if there are any issues.

**Comment by gaoyifan** [comment]
http://mirrors.ustc.edu.cn/julia/
同步完成，欢迎使用

**Comment by staticfloat** [comment]
Hmmm, now that I look at it, we should probably delete the `tmp` folder after running the mirroring script.  :)

**Comment by staticfloat** [comment]
Also, [the `METADATA.jl.git` directory](http://mirrors.ustc.edu.cn/julia/metadata/METADATA.jl.git/) seems to be giving an HTTP 403 error; I assume there are some bad permissions?  What should we do about that; `chown -R $(id -u):$(id -r)`?

**Comment by staticfloat** [comment]
(Also, according to `status.json` it looks like the `METADATA.jl` clone failed)

**Comment by zhsj** [comment]
@staticfloat METADATA.jl.git on server is `drwx------ 7 mirror mirror` , the owner and group is correct, but the perm should be `0755`. I think the this dir is created by the mirror script?

BTW, I see the sync container already runs 3 hours. But there's no output. Does this script must log to file, and can't log to stdout/stderr?

**Comment by staticfloat** [comment]
Hmmm, it looks to me like the `git` clone is failing.  When I run gitsha  locally via:
```
docker build -t pkgmirror . && docker run --entrypoint=/bin/bash -v /tmp/logs:/logs -v /tmp/data:/data -e TO=/data -ti pkgmirror /sync.sh
```

I get the following output:
```
[2018-10-28 20:13:55]WARNING:Setting mirror_releases changed from None to True.
[2018-10-28 20:13:55]WARNING:Setting mirror_metadata changed from None to True.
[2018-10-28 20:13:55]WARNING:Setting mirror_packages changed from None to True.
[2018-10-28 20:13:55]WARNING:Setting registries changed from None to {'General': 'https://github.com/JuliaRegistries/General.git'}.
[2018-10-28 20:13:55]WARNING:Setting sync_latest changed from None to False.
[2018-10-28 20:13:55]WARNING:Setting ignore_invalid changed from None to False.
[2018-10-28 20:13:55]WARNING:Setting ignore_404 changed from None to False.
^[[Ash: /data/tmp/tmpuudwfgin/hooks/post-update: Permission denied
[2018-10-28 20:16:33]ERROR:Failed to update metadata
Traceback (most recent call last):
  File "/julia-mirror/scripts/mirror_julia.py", line 556, in <module>
    main()
  File "/julia-mirror/scripts/mirror_julia.py", line 548, in main
    try_update('metadata', update_metadata, config, status)
  File "/julia-mirror/scripts/mirror_julia.py", line 537, in try_update
    raise e
  File "/julia-mirror/scripts/mirror_julia.py", line 532, in try_update
    update(config, status)
  File "/julia-mirror/scripts/mirror_julia.py", line 352, in update_metadata
    repo = git.Repo(config.metadata_dir)
  File "/usr/lib/python3.6/site-packages/git/repo/base.py", line 168, in __init__
    raise InvalidGitRepositoryError(epath)
git.exc.InvalidGitRepositoryError: /data/metadata/METADATA.jl
```

How are you running it, and are you getting a similar error?

**Comment by sunoru** [comment]
There was a bug in `mirror_julia.py` that cloned directories didn't have correct permission settings, which is just fixed.

I suggest you remove the entire `metadata` folder and run the script again.

And it is also recommended to add `--logging-file` and `--mirror-name` for a production environment.

By the way, because the server of git requires Smart HTTP support, you need to use `git-http-backend` to make it work. See https://github.com/zjulug/git-http-backend-docker

In fact all the directories whose names end with ".git" can be hidden in the directory listing, since it's only for git clone use.

**Comment by volltin** [comment]
```*********** 8< ***********
fatal: Not a git repository (or any of the parent directories): .git
hejiyan@mirrors2:~$ cd /srv/repo/julia/
hejiyan@mirrors2:/srv/repo/julia$ l
